### ISSUE TITLE
アイコンが参照できない状態でビルドされている？

### ISSUE THREAD

**Issue by bino98** [thinreports/thinreports-section-editor#43]
とても便利なライブラリを開発いただき、ありがとうございます。

section editorを https://github.com/thinreports/thinreports-section-editor/releases/tag/v1.0.0-dev からダウンロードさせていただいたのですが(mac)、アプリケーション内で使用されているアイコンが抜けているようです。

手元でのビルドは試せていないので原因究明まではできてはいません。

<img width="508" alt="スクリーンショット 2022-03-18 18 03 43" src="https://user-images.githubusercontent.com/353699/158972882-5df43dc7-b9fd-4c9a-a322-fc55154ce9c0.png">

**Comment by hidakatsuya** [comment]
ご報告ありがとうございます。確認してみます。

**Comment by hidakatsuya** [comment]
production でビルドしたとき、WebFont が参照できない状態になるようです。development ビルドでは問題ないため、electron ビルドの問題だと思います。

**Comment by hidakatsuya** [comment]
以下は、`npm run electron:build` して `dist_electron/` の editor を起動した場合の devtool の Sources:

![image](https://user-images.githubusercontent.com/739339/160290355-54eef574-de87-4d36-ab28-f2a1a8ed4262.png)

`fonts` が `Electron Isolated Context` に含まれていないためこの事象が生じている。

**Comment by hidakatsuya** [comment]
> contextIsolation boolean (任意) - Electron APIと指定された preload スクリプトを別々のJavaScriptコンテキストで実行するかどうか。 省略値は true です。 preload スクリプトが実行されるコンテキストでは、専用の document および window グローバルと、独自の JavaScript ビルドインのセット (Array, Object, JSON など) にのみアクセスできます。これらすべてはロードされたコンテンツからは見えません。 Electron API は preload スクリプトでのみ利用可能で、読み込まれたページでは利用できません。 このオプションは、信頼できない可能性のあるリモートコンテンツをロードする際に使用します。ロードされたコンテンツが preload スクリプトや使用する Electron API を改ざんできないようにするためです。 このオプションは、[Chrome のコンテンツスクリプト](https://developer.chrome.com/extensions/content_scripts#execution-environment) のものと同じ技術を使用しています。 Console タブの一番上のコンボボックスの中にある 'Electron Isolated Context' という項目を選択することによって、開発者ツールでこのコンテキストにアクセスできます。
> https://www.electronjs.org/ja/docs/latest/api/browser-window#new-browserwindowoptions

`contextIsolation` は有効にしている。省略しているためデフォルトの true となる。
https://github.com/thinreports/thinreports-section-editor/blob/2c72c9c0b6f3a516a606f9f0e5ed0c7bb9686f87/src/background.ts#L53-L59

**Comment by hidakatsuya** [comment]
一方、`npm run electron:serve` の場合 (`NODE_ENV != "development"`)は `fonts` は `Electron Isolated Context` に含まれている。
![image](https://user-images.githubusercontent.com/739339/160290828-f0f52154-7203-48a4-8a8f-7615a290e0a1.png)

**Comment by hidakatsuya** [comment]
開発版 (macOS) https://github.com/thinreports/thinreports-section-editor/releases/tag/v1.0.0-dev で確認したところ、アイコンが表示されていました。
![image](https://user-images.githubusercontent.com/739339/167338233-8de38809-0966-4e44-80d4-dc0e15416c08.png)
